title: Import Cloud Config Request
x-stoplight:
  id: ykvtb3ll3v3cw
type: object
examples:
- endpointConfig:
    control:
      commandResponse:
        connections:
        - description: MQTT_TEST
          name: MQTT_TEST
          options:
            additional:
              cleanSession: true
              clientId: FX9600FCC017
              debug: false
              keepAlive: 60
              qos: 0
              reconnectDelay: 1
              reconnectDelayMax: 5
            enableSecurity: false
            endpoint:
              hostName: broker.emqx.io
              port: 1883
              protocol: tcp
            publishTopic:
            - FX9600FCC017/rsp
            security:
              CACertificateFileLocation: /home/root/broker.emqx.io-ca.crt
              installedCertificateName: Server
              installedCertificateType: server
              keyAlgorithm: RS256
              keyFormat: PEM
              verifyHostName: false
              verifyPeer: false
            subscribeTopic:
            - FX9600FCC017/cmd
          type: mqtt
        enableLocalRest: true
    data:
      event:
        connections:
        - additionalOptions:
            batching: null
            retention:
              maxEventRetentionTimeInMin: 500
              maxNumEvents: 150000
              throttle: 500
          description: MQTT_TEST
          name: MQTT_TEST
          options:
            additional:
              cleanSession: true
              clientId: FX9600FCC017
              debug: false
              keepAlive: 60
              qos: 0
              reconnectDelay: 1
              reconnectDelayMax: 5
            enableSecurity: false
            endpoint:
              hostName: broker.emqx.io
              port: 1883
              protocol: tcp
            publishTopic:
            - FX9600FCC017/tevents
            security:
              CACertificateFileLocation: /home/root/broker.emqx.io-ca.crt
              installedCertificateName: Server
              installedCertificateType: server
              keyAlgorithm: RS256
              keyFormat: PEM
              verifyHostName: false
              verifyPeer: false
            subscribeTopic: []
          type: mqtt
    management:
      commandResponse:
        connections:
        - description: MQTT_TEST
          name: MQTT_TEST
          options:
            additional:
              cleanSession: true
              clientId: FX9600FCC017
              debug: false
              keepAlive: 60
              qos: 0
              reconnectDelay: 1
              reconnectDelayMax: 5
            enableSecurity: false
            endpoint:
              hostName: broker.emqx.io
              port: 1883
              protocol: tcp
            publishTopic:
            - FX9600FCC017/rsp
            security:
              CACertificateFileLocation: /home/root/broker.emqx.io-ca.crt
              installedCertificateName: Server
              installedCertificateType: server
              keyAlgorithm: RS256
              keyFormat: PEM
              verifyHostName: false
              verifyPeer: false
            subscribeTopic:
            - FX9600FCC017/cmd
          type: mqtt
        enableLocalRest: true
      event:
        connections:
        - description: MQTT_TEST
          name: MQTT_TEST
          options:
            additional:
              cleanSession: true
              clientId: FX9600FCC017
              debug: false
              keepAlive: 60
              qos: 0
              reconnectDelay: 1
              reconnectDelayMax: 5
            enableSecurity: false
            endpoint:
              hostName: broker.emqx.io
              port: 1883
              protocol: tcp
            publishTopic:
            - FX9600FCC017/mevents
            subscribeTopic: []
          type: mqtt
description: Imports Cloud Configuration
properties:
  endpointConfig:
    type: object
    x-stoplight:
      id: lq94d22unugji
    properties:
      data:
        type: object
        x-stoplight:
          id: 3v14mz45s5qlx
        properties:
          event:
            $ref: ../shared/event.v1.yaml
            x-stoplight:
              id: fkuxodt97brxb
      control:
        type: object
        x-stoplight:
          id: zuhe4tlmzph3e
        properties:
          commandResponse:
            $ref: ../shared/ctrl_cmdresp.yaml
            x-stoplight:
              id: dkgtkjtr2tvz7
      management:
        type: object
        x-stoplight:
          id: kceoheiqj6ag1
        properties:
          event:
            $ref: ../shared/mgmt_event.yaml
            x-stoplight:
              id: xfq7xd0vq2l5b
          commandResponse:
            $ref: ../shared/mgmt_cmdresp.yaml
            x-stoplight:
              id: p5o8vwwnyv7ui
required:
- endpointConfig
