#!/usr/bin/env python3
"""
build_openapi.py
================
Build the REST API spec from ``RestAPI/paths/`` (your editable source).
On every run it:
 * auto-generates ``RestAPI/openapi.yaml`` from ``FX90.yaml`` + ``paths/``,
 * inlines each path file into one bundled document,
 * merges ``RestAPI/operation_descriptions/*.md`` into operation descriptions,
 * writes ``RestAPI/FX90-rest-api.yaml`` for Swagger UI,
then validates references (and ``openapi-spec-validator`` when installed).
You only edit ``RestAPI/paths/``. Do not edit ``openapi.yaml`` or
``FX90-rest-api.yaml`` — both are generated.
Run:
   python RestAPI/scripts/build_openapi.py
"""
from __future__ import annotations
import shutil
from collections import OrderedDict
from pathlib import Path
import yaml
REST_DIR = Path(__file__).resolve().parent.parent
MONOLITH = REST_DIR / "FX90.yaml"
ROOT_IN = REST_DIR / "openapi.yaml"
BUNDLED_OUT = REST_DIR / "FX90-rest-api.yaml"
SCHEMAS_DIR = REST_DIR / "schemas"
PATHS_DIR = REST_DIR / "paths"
OP_DESCRIPTIONS_DIR = REST_DIR / "operation_descriptions"
HTTP_METHODS = frozenset(
   {"get", "put", "post", "delete", "patch", "head", "options", "trace"}
)
TAG_TO_FOLDER = {
   "Login": "login",
   "System": "system",
   "Network": "network",
   "Control": "control",
   "Region": "region",
   "Gpio": "gpio",
   "App-led": "led",
   "Stack-led": "led",
   "Logs": "logs",
   "Date&Time": "datetime",
   "Certificate": "certificates",
   "Firmware": "firmware",
   "userapp": "userapps",
   "Ble": "ble",
   "ImpinjGen2X": "impinj",
}
PATH_FOLDER_OVERRIDE = {
   "/cloud/cloudConfig": "network",
}
AUTO_GENERATED_HEADER = (
   "# AUTO-GENERATED by RestAPI/scripts/build_openapi.py — do not edit.\n"
   "# Edit RestAPI/paths/ and run: python RestAPI/scripts/build_openapi.py\n"
)
def _represent_ordereddict(dumper, data):
   return dumper.represent_mapping("tag:yaml.org,2002:map", data.items())
yaml.add_representer(OrderedDict, _represent_ordereddict)
yaml.SafeDumper.add_representer(OrderedDict, _represent_ordereddict)
def load_yaml(path: Path):
   with path.open("r", encoding="utf-8") as fh:
       return yaml.safe_load(fh)
def dump_yaml(path: Path, data, *, header: str = "") -> None:
   path.parent.mkdir(parents=True, exist_ok=True)
   with path.open("w", encoding="utf-8") as fh:
       if header:
           fh.write(header)
       yaml.safe_dump(
           data,
           fh,
           sort_keys=False,
           allow_unicode=True,
           default_flow_style=False,
           width=4096,
       )
def path_filename(api_path: str) -> str:
   segments = [s for s in api_path.strip("/").split("/") if s]
   if segments and segments[0] == "cloud":
       segments = segments[1:]
   cleaned = [s.replace("{", "").replace("}", "") for s in segments]
   return "_".join(cleaned) if cleaned else "root"
def folder_for_path(api_path: str, item: dict) -> str:
   if api_path in PATH_FOLDER_OVERRIDE:
       return PATH_FOLDER_OVERRIDE[api_path]
   for method, op in item.items():
       if isinstance(op, dict) and op.get("tags"):
           tag = str(op["tags"][0]).strip()
           return TAG_TO_FOLDER.get(tag, "misc")
   return "misc"
def path_file_for_api_path(api_path: str, path_item: dict, paths_dir: Path) -> Path:
   folder = folder_for_path(api_path, path_item)
   fname = path_filename(api_path)
   return paths_dir / folder / f"{fname}.yaml"
def build_openapi_root(monolith: dict, paths_dir: Path, existing_root: dict | None = None) -> tuple[OrderedDict, list[str]]:
   paths = monolith.get("paths", {})
   schemas = OrderedDict(monolith.get("components", {}).get("schemas", {}))
   if existing_root:
       existing_schemas = existing_root.get("components", {}).get("schemas", {})
       for name, schema in existing_schemas.items():
           if name not in schemas:
               schemas[name] = schema
   root = OrderedDict()
   root["openapi"] = monolith.get("openapi", "3.1.0")
   root["info"] = monolith.get("info", {})
   if "externalDocs" in monolith:
       root["externalDocs"] = monolith["externalDocs"]
   if "servers" in monolith:
       root["servers"] = monolith["servers"]
   if "tags" in monolith:
       root["tags"] = monolith["tags"]
   root_paths = OrderedDict()
   missing: list[str] = []
   for api_path, item in paths.items():
       path_file = path_file_for_api_path(api_path, item, paths_dir)
       if not path_file.is_file():
           missing.append(str(path_file.relative_to(paths_dir.parent)))
           continue
       rel = path_file.relative_to(paths_dir.parent).as_posix()
       root_paths[api_path] = {"$ref": f"./{rel}"}
   root["paths"] = root_paths
   components = OrderedDict()
   sec = monolith.get("components", {}).get("securitySchemes")
   if sec:
       components["securitySchemes"] = sec
   components["schemas"] = schemas
   root["components"] = components
   return root, missing
def schema_name_from_ref(ref: str) -> str:
   return Path(ref).name[: -len(".yaml")] if ref.endswith(".yaml") else Path(ref).name
def normalize_schema_ref(ref: str) -> str:
   if ref.startswith("#/components/schemas/"):
       return ref
   if ref.endswith(".yaml"):
       return f"#/components/schemas/{schema_name_from_ref(ref)}"
   if "#/components/schemas/" in ref:
       return f"#/components/schemas/{ref.split('/components/schemas/')[-1]}"
   return ref
def load_rest_operation_descriptions() -> dict[str, str]:
   descriptions: dict[str, str] = {}
   if not OP_DESCRIPTIONS_DIR.is_dir():
       return descriptions
   for path in sorted(OP_DESCRIPTIONS_DIR.iterdir()):
       if path.suffix.lower() != ".md" or path.name.lower() == "readme.md":
           continue
       if path.name.startswith("_"):
           continue
       text = path.read_text(encoding="utf-8-sig").strip()
       if text:
           descriptions[path.stem] = text
   return descriptions
def description_key(method: str, api_path: str, operation_id: str | None) -> str:
   if operation_id:
       return operation_id
   safe = api_path.strip("/").replace("/", "__")
   return f"{method.upper()}__{safe}"
def apply_operation_descriptions(
   path_item: dict,
   api_path: str,
   descriptions: dict[str, str],
) -> int:
   applied = 0
   for method, operation in path_item.items():
       if method not in HTTP_METHODS or not isinstance(operation, dict):
           continue
       key = description_key(method, api_path, operation.get("operationId"))
       md = descriptions.get(key)
       if md:
           operation["description"] = md
           applied += 1
   return applied
def to_internal_refs(node):
   if isinstance(node, dict):
       return {
           key: normalize_schema_ref(value) if key == "$ref" and isinstance(value, str) else to_internal_refs(value)
           for key, value in node.items()
       }
   if isinstance(node, list):
       return [to_internal_refs(v) for v in node]
   return node
def collect_refs(node, out):
   if isinstance(node, dict):
       for key, value in node.items():
           if key == "$ref" and isinstance(value, str) and value.startswith("#/components/schemas/"):
               out.add(value.split("/")[-1])
           else:
               collect_refs(value, out)
   elif isinstance(node, list):
       for v in node:
           collect_refs(v, out)
def rewrite_path_file_refs(path: Path) -> bool:
   text = path.read_text(encoding="utf-8")
   original = text
   for line in text.splitlines():
       if "$ref:" not in line or "schemas/" not in line:
           continue
       ref = line.split("$ref:", 1)[1].strip()
       if not ref.endswith(".yaml"):
           continue
       name = schema_name_from_ref(ref)
       text = text.replace(f"$ref: {ref}", f"$ref: ../../openapi.yaml#/components/schemas/{name}")
   if text != original:
       path.write_text(text, encoding="utf-8")
       return True
   return False
def cleanup_legacy_layout() -> None:
   if PATHS_DIR.is_dir():
       fixes = sum(1 for p in PATHS_DIR.rglob("*.yaml") if rewrite_path_file_refs(p))
       if fixes:
           print(f"Legacy fix     : updated {fixes} path file(s) with old schemas/ refs")
   if SCHEMAS_DIR.exists():
       shutil.rmtree(SCHEMAS_DIR)
       print("Legacy fix     : removed RestAPI/schemas/")
def generate_openapi_yaml() -> int:
   """Regenerate openapi.yaml from FX90.yaml metadata and paths/ files."""
   if not MONOLITH.is_file():
       raise SystemExit(f"Missing {MONOLITH.name} (needed to generate openapi.yaml)")
   if not PATHS_DIR.is_dir():
       raise SystemExit(f"Missing {PATHS_DIR.relative_to(REST_DIR.parent)} — nothing to build")
   doc = load_yaml(MONOLITH)
   existing_root = load_yaml(ROOT_IN) if ROOT_IN.is_file() else None
   root, missing = build_openapi_root(doc, PATHS_DIR, existing_root)
   if missing:
       print("\nMissing path file(s) (expected under RestAPI/paths/):")
       for rel in missing:
           print(f"  {rel}")
       raise SystemExit(1)
   dump_yaml(ROOT_IN, root, header=AUTO_GENERATED_HEADER)
   return len(root.get("paths", {}))
def load_schema_entry(name: str, ref_obj, base: Path) -> dict:
   if not isinstance(ref_obj, dict):
       raise ValueError(f"Cannot load schema {name!r}: {ref_obj!r}")
   if "$ref" not in ref_obj:
       return to_internal_refs(ref_obj)
   ref = ref_obj["$ref"]
   if isinstance(ref, str) and ref.endswith(".yaml"):
       return to_internal_refs(load_yaml((base / ref).resolve()))
   if isinstance(ref, str) and ref.startswith("#/components/schemas/"):
       return ref_obj
   raise ValueError(f"Cannot load schema {name!r}: {ref_obj!r}")
def main() -> None:
   cleanup_legacy_layout()
   path_refs = generate_openapi_yaml()
   root = load_yaml(ROOT_IN)
   op_descriptions = load_rest_operation_descriptions()
   bundled = OrderedDict()
   for key in ("openapi", "info", "externalDocs", "servers", "tags"):
       if key in root:
           bundled[key] = root[key]
   paths_out = OrderedDict()
   op_count = 0
   desc_applied = 0
   for path, ref_obj in root.get("paths", {}).items():
       ref = ref_obj["$ref"]
       item = load_yaml((ROOT_IN.parent / ref).resolve())
       desc_applied += apply_operation_descriptions(item, path, op_descriptions)
       paths_out[path] = to_internal_refs(item)
       op_count += sum(1 for m in paths_out[path] if m in HTTP_METHODS)
   bundled["paths"] = paths_out
   components = OrderedDict()
   src_components = root.get("components", {})
   if "securitySchemes" in src_components:
       components["securitySchemes"] = src_components["securitySchemes"]
   schemas_out = OrderedDict()
   for name, ref_obj in src_components.get("schemas", {}).items():
       schemas_out[name] = load_schema_entry(name, ref_obj, ROOT_IN.parent)
   components["schemas"] = schemas_out
   bundled["components"] = components
   with BUNDLED_OUT.open("w", encoding="utf-8") as fh:
       fh.write(
           "# AUTO-GENERATED by RestAPI/scripts/build_openapi.py — do not edit.\n"
           "# Edit RestAPI/paths/ and rebuild.\n"
       )
       yaml.safe_dump(
           bundled,
           fh,
           sort_keys=False,
           allow_unicode=True,
           default_flow_style=False,
           width=4096,
       )
   declared = set(schemas_out.keys())
   used: set = set()
   collect_refs(paths_out, used)
   collect_refs(schemas_out, used)
   missing = sorted(used - declared)
   print(f"Generated      : {ROOT_IN.name} ({path_refs} path refs)")
   print(f"Paths          : {len(paths_out)}")
   print(f"Operations     : {op_count}")
   print(f"Schemas        : {len(schemas_out)}")
   print(f"Refs used       : {len(used)}")
   print(f"REST op docs    : {len(op_descriptions)} file(s), {desc_applied} operation(s) updated")
   print(f"Bundled output  : {BUNDLED_OUT.name}")
   if missing:
       print("\nBROKEN REFERENCES (no matching schema):")
       for m in missing:
           print(f"  #/components/schemas/{m}")
   else:
       print("Reference check : OK (all $ref targets resolve)")
   try:
       from openapi_spec_validator import validate as _validate  # type: ignore
       _validate(load_yaml(BUNDLED_OUT))
       print("openapi-spec-validator: VALID")
   except ImportError:
       print("openapi-spec-validator: not installed (skipped optional deep validation)")
   except Exception as exc:  # noqa: BLE001
       print(f"openapi-spec-validator: ISSUES -> {exc}")
   if missing:
       raise SystemExit(1)
if __name__ == "__main__":
   main()