#!/usr/bin/env python3
"""
build_fxr90_rest_api.py
========================
Build ``RestAPI/FXR90-rest-api.yaml`` for Swagger UI by combining:

 * **Schemas + operation metadata** from ``RestDeveloperfile.yaml`` (repo root)
 * **Rich operation descriptions** from ``RestAPI/operation_descriptions/*.md``

Run whenever ``RestDeveloperfile.yaml`` changes:

    python RestAPI/scripts/build_fxr90_rest_api.py

Do not edit ``FXR90-rest-api.yaml`` by hand — it is generated.
"""
from __future__ import annotations

import copy
import sys
from collections import OrderedDict
from pathlib import Path

import yaml

# Reuse normalization, schema flattening, and markdown merge from the REST builder.
from build_openapi import (  # noqa: E402
    HTTP_METHODS,
    collect_refs,
    description_key,
    extract_nested_schemas,
    load_rest_operation_descriptions,
    normalize_openapi_document,
)

REST_DIR = Path(__file__).resolve().parent.parent
ROOT = REST_DIR.parent
DEVELOPER_SPEC = ROOT / "RestDeveloperfile.yaml"
BUNDLED_OUT = REST_DIR / "FXR90-rest-api.yaml"
AUTO_HEADER = (
    "# AUTO-GENERATED by RestAPI/scripts/build_fxr90_rest_api.py — do not edit.\n"
    "# Source schema: RestDeveloperfile.yaml\n"
    "# Descriptions: RestAPI/operation_descriptions/*.md\n"
    "# Rebuild: python RestAPI/scripts/build_fxr90_rest_api.py\n"
)

# Fallback when RestDeveloperfile omits operationId (path+method -> markdown stem).
# Only list entries that cannot be resolved via operationId + case-insensitive match.
PATH_METHOD_ALIASES: dict[tuple[str, str], str] = {
    ("GET", "/cloud/preSelection"): "getPreSelection",
    ("PUT", "/cloud/preSelection"): "setPreSelection",
    ("PUT", "/cloud/updatePassword"): "updatePassword",
    # Reserved for when developer restores missing /cloud/logs in RestDeveloperfile.yaml
    ("GET", "/cloud/logs"): "getLogs",
    ("PUT", "/cloud/logs"): "setLogs",
    ("GET", "/cloud/gpo"): "getGpoStatus",
    ("GET", "/cloud/eSimConfig"): "getEsimConfig",
    ("GET", "/cloud/logs/syslog"): "getLogsSyslog",
    ("DELETE", "/cloud/logs/syslog"): "delLogsSyslog",
    ("GET", "/cloud/logs/RcLog"): "getRcLog",
    ("GET", "/cloud/logs/RgWarningLog"): "getRgWarningLog",
    ("GET", "/cloud/logs/RgErrorLog"): "getRgErrorLog",
    ("GET", "/cloud/logs/radioPacketLog"): "getRadioPacketLog",
    ("DELETE", "/cloud/logs/radioPacketLog"): "delRadioPacketLog",
    ("GET", "/cloud/ntpServer"): "getNtpServer",
}


def load_yaml(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def dump_yaml(path: Path, data: dict) -> None:
    with path.open("w", encoding="utf-8") as fh:
        fh.write(AUTO_HEADER)
        yaml.safe_dump(
            data,
            fh,
            sort_keys=False,
            allow_unicode=True,
            default_flow_style=False,
            width=4096,
        )


def case_insensitive_descriptions(descriptions: dict[str, str]) -> dict[str, str]:
    """Allow operationId / markdown filename casing differences."""
    out = dict(descriptions)
    for key, text in descriptions.items():
        out.setdefault(key.lower(), text)
    return out


def lookup_description(
    method: str,
    api_path: str,
    operation_id: str | None,
    descriptions: dict[str, str],
) -> str | None:
    candidates: list[str] = []
    alias = PATH_METHOD_ALIASES.get((method.upper(), api_path))
    if alias:
        candidates.append(alias)
    if operation_id:
        candidates.append(operation_id)
    candidates.append(description_key(method, api_path, operation_id))
    for key in candidates:
        if key in descriptions:
            return descriptions[key]
        lower = key.lower()
        if lower in descriptions:
            return descriptions[lower]
    return None


def apply_markdown_descriptions(
    paths: dict,
    descriptions: dict[str, str],
) -> tuple[int, list[str]]:
    applied = 0
    missing: list[str] = []
    for api_path, path_item in paths.items():
        if not isinstance(path_item, dict):
            continue
        for method, operation in path_item.items():
            if method not in HTTP_METHODS or not isinstance(operation, dict):
                continue
            md = lookup_description(method, api_path, operation.get("operationId"), descriptions)
            if md:
                operation["description"] = md
                applied += 1
            else:
                key = description_key(method, api_path, operation.get("operationId"))
                missing.append(f"{method.upper()} {api_path} ({key})")
    return applied, missing


def main() -> int:
    if not DEVELOPER_SPEC.is_file():
        print(f"Missing developer spec: {DEVELOPER_SPEC}", file=sys.stderr)
        return 1

    spec = load_yaml(DEVELOPER_SPEC)
    bundled = copy.deepcopy(spec)

    # Ensure OrderedDict-friendly top-level keys for stable output.
    out = OrderedDict()
    for key in ("openapi", "info", "externalDocs", "servers", "tags"):
        if key in bundled:
            out[key] = bundled[key]

    paths = bundled.get("paths", {})
    if not isinstance(paths, dict):
        print("Developer spec has no paths section.", file=sys.stderr)
        return 1

    descriptions = case_insensitive_descriptions(load_rest_operation_descriptions())
    desc_applied, desc_missing = apply_markdown_descriptions(paths, descriptions)
    out["paths"] = paths

    components = OrderedDict()
    src_components = bundled.get("components", {})
    if isinstance(src_components, dict):
        if "securitySchemes" in src_components:
            components["securitySchemes"] = src_components["securitySchemes"]
        schemas = OrderedDict(src_components.get("schemas", {}) or {})
    else:
        schemas = OrderedDict()

    comp_flat_count = 0
    if schemas:
        flattened, comp_flat_count = extract_nested_schemas(dict(schemas))
        schemas = OrderedDict(flattened)

    components["schemas"] = schemas
    out["components"] = components

    out = normalize_openapi_document(out)
    dump_yaml(BUNDLED_OUT, out)

    declared = set(schemas.keys())
    used: set = set()
    collect_refs(out.get("paths", {}), used)
    collect_refs(schemas, used)
    missing_refs = sorted(used - declared)
    op_count = sum(
        1
        for path_item in paths.values()
        if isinstance(path_item, dict)
        for m in path_item
        if m in HTTP_METHODS
    )

    print(f"Source spec     : {DEVELOPER_SPEC.relative_to(REST_DIR.parent)}")
    print(f"Paths           : {len(paths)}")
    print(f"Operations      : {op_count}")
    print(f"Schemas         : {len(schemas)}")
    print(f"Op docs applied : {desc_applied} / {op_count}")
    print(f"Schema flatten  : {comp_flat_count} nested sub-schema(s)")
    print(f"Output          : {BUNDLED_OUT.relative_to(REST_DIR.parent)}")

    if desc_missing:
        print(f"\nNo markdown description ({len(desc_missing)} operation(s)):")
        for line in desc_missing[:15]:
            print(f"  {line}")
        if len(desc_missing) > 15:
            print(f"  ... and {len(desc_missing) - 15} more")

    if missing_refs:
        print("\nBROKEN REFERENCES (no matching schema):")
        for name in missing_refs:
            print(f"  #/components/schemas/{name}")
        return 1

    print("Reference check : OK")
    try:
        from openapi_spec_validator import validate as _validate  # type: ignore

        _validate(load_yaml(BUNDLED_OUT))
        print("openapi-spec-validator: VALID")
    except ImportError:
        print("openapi-spec-validator: not installed (skipped)")
    except Exception as exc:  # noqa: BLE001
        print(f"openapi-spec-validator: ISSUES -> {exc}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
