type: object
properties:
  GPIO-LED:
    type: string
  READER-GATEWAY:
    type: object
    properties:
      batching:
        type: array
        items:
          type: object
          properties:
            maxPayloadSizePerReport:
              type: number
            reportingInterval:
              type: number
      endpointConfig:
        type: object
        properties:
          control:
            type: object
            properties:
              commandResponse:
                type: object
                properties:
                  enableLocalRest:
                    type: boolean
                  connections:
                    type: array
                    items:
                      type: object
                      properties:
                        description:
                          type: string
                        name:
                          type: string
                        options:
                          type: object
                          properties:
                            additional:
                              type: object
                              properties:
                                cleanSession:
                                  type: boolean
                                clientId:
                                  type: string
                                debug:
                                  type: boolean
                                keepAlive:
                                  type: number
                                qos:
                                  type: number
                                reconnectDelay:
                                  type: number
                                reconnectDelayMax:
                                  type: number
                            enableSecurity:
                              type: boolean
                            endpoint:
                              type: object
                              properties:
                                hostName:
                                  type: string
                                port:
                                  type: number
                                protocol:
                                  type: string
                            publishTopic:
                              type: array
                              items:
                                type: string
                            security:
                              type: object
                              properties:
                                CACertificateFileLocation:
                                  type: string
                                installedCertificateName:
                                  type: string
                                installedCertificateType:
                                  type: string
                                keyAlgorithm:
                                  type: string
                                keyFormat:
                                  type: string
                                privateKeyFileLocation:
                                  type: string
                                publicKeyFileLocation:
                                  type: string
                                verifyHostName:
                                  type: boolean
                                verifyPeer:
                                  type: boolean
                            subscribeTopic:
                              type: array
                              items:
                                type: string
                        type:
                          type: string
          data:
            type: object
            properties:
              batching:
                type: object
                properties:
                  maxPayloadSizePerReport:
                    type: number
                  reportingInterval:
                    type: number
              event:
                type: object
                properties:
                  connections:
                    type: array
                    items:
                      type: object
                      properties:
                        additionalOptions:
                          type: object
                          properties:
                            batching:
                              type: object
                              properties:
                                maxPayloadSizePerReport:
                                  type: number
                                reportingInterval:
                                  type: number
                            retention:
                              type: object
                              properties:
                                maxEventRetentionTimeInMin:
                                  type: number
                                maxNumEvents:
                                  type: number
                                throttle:
                                  type: number
                        description:
                          type: string
                        name:
                          type: string
                        options:
                          type: object
                          properties:
                            additional:
                              type: object
                              properties:
                                cleanSession:
                                  type: boolean
                                clientId:
                                  type: string
                                debug:
                                  type: boolean
                                keepAlive:
                                  type: number
                                qos:
                                  type: number
                                reconnectDelay:
                                  type: number
                                reconnectDelayMax:
                                  type: number
                            enableSecurity:
                              type: boolean
                            endpoint:
                              type: object
                              properties:
                                hostName:
                                  type: string
                                port:
                                  type: number
                                protocol:
                                  type: string
                            publishTopic:
                              type: array
                              items:
                                type: string
                            security:
                              type: object
                              properties:
                                CACertificateFileLocation:
                                  type: string
                                installedCertificateName:
                                  type: string
                                installedCertificateType:
                                  type: string
                                keyAlgorithm:
                                  type: string
                                keyFormat:
                                  type: string
                                privateKeyFileLocation:
                                  type: string
                                publicKeyFileLocation:
                                  type: string
                                verifyHostName:
                                  type: boolean
                                verifyPeer:
                                  type: boolean
                            subscribeTopic:
                              type: array
                              items:
                                type: string
                        type:
                          type: string
              retention:
                type: object
                properties:
                  maxEventRetentionTimeInMin:
                    type: number
                  maxNumEvents:
                    type: number
                  throttle:
                    type: number
          management:
            type: object
            properties:
              commandResponse:
                type: object
                properties:
                  enableLocalRest:
                    type: boolean
                  connections:
                    type: array
                    items:
                      type: object
                      properties:
                        description:
                          type: string
                        name:
                          type: string
                        options:
                          type: object
                          properties:
                            additional:
                              type: object
                              properties:
                                cleanSession:
                                  type: boolean
                                clientId:
                                  type: string
                                debug:
                                  type: boolean
                                keepAlive:
                                  type: number
                                qos:
                                  type: number
                                reconnectDelay:
                                  type: number
                                reconnectDelayMax:
                                  type: number
                            enableSecurity:
                              type: boolean
                            endpoint:
                              type: object
                              properties:
                                hostName:
                                  type: string
                                port:
                                  type: number
                                protocol:
                                  type: string
                            publishTopic:
                              type: array
                              items:
                                type: string
                            security:
                              type: object
                              properties:
                                CACertificateFileLocation:
                                  type: string
                                installedCertificateName:
                                  type: string
                                installedCertificateType:
                                  type: string
                                keyAlgorithm:
                                  type: string
                                keyFormat:
                                  type: string
                                privateKeyFileLocation:
                                  type: string
                                publicKeyFileLocation:
                                  type: string
                                verifyHostName:
                                  type: boolean
                                verifyPeer:
                                  type: boolean
                            subscribeTopic:
                              type: array
                              items:
                                type: string
                        type:
                          type: string
              event:
                type: object
                properties:
                  connections:
                    type: array
                    items:
                      type: object
                      properties:
                        additionalOptions:
                          type: object
                          properties:
                            retention:
                              type: object
                              properties:
                                maxEventRetentionTimeInMin:
                                  type: number
                                maxNumEvents:
                                  type: number
                                throttle:
                                  type: number
                        description:
                          type: string
                        name:
                          type: string
                        options:
                          type: object
                          properties:
                            additional:
                              type: object
                              properties:
                                cleanSession:
                                  type: boolean
                                clientId:
                                  type: string
                                debug:
                                  type: boolean
                                keepAlive:
                                  type: number
                                qos:
                                  type: number
                                reconnectDelay:
                                  type: number
                                reconnectDelayMax:
                                  type: number
                            enableSecurity:
                              type: boolean
                            endpoint:
                              type: object
                              properties:
                                hostName:
                                  type: string
                                port:
                                  type: number
                                protocol:
                                  type: string
                            publishTopic:
                              type: array
                              items:
                                type: string
                            security:
                              type: object
                              properties:
                                CACertificateFileLocation:
                                  type: string
                                installedCertificateName:
                                  type: string
                                installedCertificateType:
                                  type: string
                                keyAlgorithm:
                                  type: string
                                keyFormat:
                                  type: string
                                privateKeyFileLocation:
                                  type: string
                                publicKeyFileLocation:
                                  type: string
                                verifyHostName:
                                  type: boolean
                                verifyPeer:
                                  type: boolean
                            subscribeTopic:
                              type: array
                              items:
                                type: string
                        type:
                          type: string
      managementEventConfig:
        type: object
        properties:
          errors:
            type: object
            properties:
              antenna:
                type: boolean
              cpu:
                type: object
                properties:
                  reportIntervalInSec:
                    type: number
                  threshold:
                    type: number
              database:
                type: boolean
              flash:
                type: object
                properties:
                  reportIntervalInSec:
                    type: number
                  threshold:
                    type: number
              ntp:
                type: boolean
              radio:
                type: boolean
              radio_control:
                type: boolean
              ram:
                type: object
                properties:
                  reportIntervalInSec:
                    type: number
                  threshold:
                    type: number
              reader_gateway:
                type: boolean
              userApp:
                type: object
                properties:
                  reportIntervalInSec:
                    type: number
                  threshold:
                    type: number
          gpiEvents:
            type: boolean
          gpoEvents:
            type: boolean
          heartbeat:
            type: object
            properties:
              fields:
                type: object
                properties:
                  radio_control:
                    type: array
                    items:
                      type: string
                  reader_gateway:
                    type: array
                    items:
                      type: string
                  system:
                    type: array
                    items:
                      type: string
                  userDefined:
                    type: object
                    properties: {}
                  userapps:
                    type: array
                    items:
                      type: string
              interval:
                type: number
          userappEvents:
            type: boolean
          warnings:
            type: object
            properties:
              cpu:
                type: object
                properties:
                  reportIntervalInSec:
                    type: number
                  threshold:
                    type: number
              database:
                type: boolean
              flash:
                type: object
                properties:
                  reportIntervalInSec:
                    type: number
                  threshold:
                    type: number
              ntp:
                type: boolean
              radio_api:
                type: boolean
              radio_control:
                type: boolean
              ram:
                type: object
                properties:
                  reportIntervalInSec:
                    type: number
                  threshold:
                    type: number
              reader_gateway:
                type: boolean
              temperature:
                type: object
                properties:
                  ambient:
                    type: number
                  pa:
                    type: number
              userApp:
                type: object
                properties:
                  reportIntervalInSec:
                    type: number
                  threshold:
                    type: number
      retention:
        type: array
        items:
          type: object
          properties:
            maxEventRetentionTimeInMin:
              type: number
            maxNumEvents:
              type: number
            throttle:
              type: number
title: Reader Configuration
description: Reader configuration returned by get_config.
